apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      # hostname: "wordpress.koothooloo.io"
      containers:
      - image: vishv/wordpress:latest
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: changeme
        - name: WORDPRESS_USERNAME
          value: admin
        - name: WORDPRESS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vishvish-wordpress
              key: password
        - name: WORDPRESS_EMAIL
          value: vish.vishvanath@gmail.com
        - name: WORDPRESS_FIRST_NAME
          value: Vish
        - name: WORDPRESS_LAST_NAME
          value: Vishvanath
        - name: WORDPRESS_BLOG_NAME
          value: Vish / London Photojournalist
        - name: MYSQL_CLIENT_CREATE_DATABASE_NAME
          value: vishvish_wordpress
        - name: MYSQL_CLIENT_CREATE_DATABASE_USER
          value: wordpress
        - name: MYSQL_CLIENT_CREATE_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vishvish-mysql
              key: password
        - name: MARIADB_ROOT_USER
          value: root
        - name: MARIADB_ROOT_PASSWORD
          value: changeme
        - name: WORDPRESS_DATABASE_USER
          value: wordpress
        - name: WORDPRESS_DATABASE_NAME
          value: vishvish_wordpress
        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vishvish-mysql
              key: password
        - name: MARIADB_HOST
          value: wordpress-mysql
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: image-store
          mountPath: /var/www/html
      volumes:
      - name: image-store
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            fsName: myfs # name of the filesystem specified in the filesystem CRD.
            clusterNamespace: rook-ceph # namespace where the Rook cluster is deployed
            # by default the path is /, but you can override and mount a specific path of the filesystem by using the path attribute
            # the path must exist on the filesystem, otherwise mounting the filesystem at that path will fail
            # path: /some/path/inside/cephfs
